# Generated by Django 3.1.3 on 2020-11-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('comorbid', models.CharField(blank=True, choices=[('DB', 'Diabeties'), ('CD', 'Cardiovascular Disease')], max_length=12, null=True)),
                ('blood_group', models.CharField(default='UNK', max_length=3)),
                ('is_smoker', models.BooleanField(default=False)),
                ('is_drinker', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('category', models.CharField(choices=[('PK', 'Painkiller'), ('BT', 'Blood thinner'), ('LX', 'Laxative'), ('AI', 'Anti inflammatory')], max_length=2)),
                ('expiry', models.DateField()),
                ('qty', models.IntegerField()),
                ('threshold_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ventilator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ICU', 'ICU'), ('GEN', 'General')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('phone_no', models.IntegerField()),
                ('insurance', models.CharField(max_length=16)),
                ('aadhar', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Admitted'), (2, 'Discharged'), (3, 'Recovered'), (4, 'Deceased')], default=1)),
                ('admit_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('bed', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.bed')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('health_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.healthdetails')),
                ('medicines', models.ManyToManyField(blank=True, to='hospital.Medicine')),
                ('next_of_kin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.kin')),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AG', 'Antigen'), ('RT', 'RT-PCR')], max_length=2)),
                ('result', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative')], max_length=1)),
                ('testing_date', models.DateTimeField()),
                ('test_duration', models.IntegerField(verbose_name='Hours until test results')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='ventilator',
            field=models.ManyToManyField(blank=True, to='hospital.Ventilator'),
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.ward'),
        ),
    ]
