# Generated by Django 3.1.3 on 2020-11-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdetails',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Mild'), (2, 'Potenitally worsening'), (3, 'Moderate severity'), (4, 'High severity'), (5, 'Requires urgent care')], default=1),
        ),
    ]
