# Generated by Django 3.1.3 on 2020-11-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_patient_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdetails',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='healthdetails',
            name='fever',
            field=models.BooleanField(default=False),
        ),
    ]
