# Generated by Django 3.1.3 on 2020-11-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20201121_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdetails',
            name='dry_cough',
            field=models.BooleanField(default=False),
        ),
    ]
