# Generated by Django 3.1.3 on 2020-11-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20201121_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdetails',
            name='severity',
        ),
    ]
