# Generated by Django 3.1.3 on 2020-11-21 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_auto_20201122_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='ventilator',
        ),
        migrations.AddField(
            model_name='bed',
            name='ventilator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.ventilator'),
        ),
    ]
