# Generated by Django 3.1.3 on 2020-11-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20201122_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='result',
            field=models.CharField(blank=True, choices=[('P', 'Positive'), ('N', 'Negative')], max_length=1),
        ),
    ]
