# Generated by Django 3.1.3 on 2020-11-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='dr', max_length=32),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
