# Generated by Django 3.1.3 on 2020-11-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_auto_20201122_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.IntegerField(default=0),
        ),
    ]
